// AUTO-GENERATED by scripts/gen-guide-content.mjs — do not edit manually

export const guideHtmlContent: Record<string, string> = {
  'valve-standards/en': `<h2>The Three Standards Bodies</h2>
<p>The global tire valve industry is governed by three major standards organizations, each representing a major automotive market:</p>
<table class="w-full text-sm border-collapse my-6"><thead><tr class="border-b-2 border-slate-200"><th class="text-left py-2 px-3">Organization</th><th class="text-left py-2 px-3">Region</th><th class="text-left py-2 px-3">Scope</th></tr></thead><tbody><tr class="border-b border-slate-100"><td class="py-2 px-3 font-medium">TRA (Tire and Rim Association)</td><td class="py-2 px-3">North America</td><td class="py-2 px-3">Tire, rim, and valve standards for the US and Canadian markets</td></tr><tr class="border-b border-slate-100"><td class="py-2 px-3 font-medium">ETRTO (European Tyre and Rim Technical Organisation)</td><td class="py-2 px-3">Europe</td><td class="py-2 px-3">Harmonized tire and valve specifications across EU member states</td></tr><tr class="border-b border-slate-100"><td class="py-2 px-3 font-medium">JATMA (Japan Automobile Tyre Manufacturers Association)</td><td class="py-2 px-3">Japan</td><td class="py-2 px-3">Japanese domestic standards for tires, rims, and valves</td></tr></tbody></table>
<h2>Key Differences</h2>
<p>While the three standards share compatible physical dimensions for most valve types, they diverge in several important areas:</p>
<h3>Test Methods</h3>
<p>Each organization defines its own test protocols for pressure retention, temperature cycling, and chemical resistance. A valve that passes TRA testing may need additional documentation to satisfy ETRTO or JATMA requirements, even if the physical product is identical.</p>
<h3>Marking and Documentation</h3>
<ul>
<li><strong>TRA</strong>: Requires specific alphanumeric designations (e.g., TR413, TR414)</li>
<li><strong>ETRTO</strong>: Uses its own designation system with cross-references to TRA equivalents</li>
<li><strong>JATMA</strong>: Follows Japanese Industrial Standards (JIS) conventions with separate part numbering</li>
</ul>
<h3>Regional Certifications</h3>
<p>OEM buyers in each region typically specify their local standard. A European automaker will reference ETRTO specifications, while a Japanese manufacturer will cite JATMA. For global suppliers, maintaining compliance documentation for all three is essential.</p>
<h2>Why Multi-Standard Compliance Matters for OEM</h2>
<p>For valve manufacturers serving global OEM customers, designing products that simultaneously meet TRA, ETRTO, and JATMA requirements eliminates the need for region-specific product variants. This means:</p>
<ul>
<li><strong>Simplified inventory</strong>: One SKU serves all markets</li>
<li><strong>Faster qualification</strong>: Pre-existing multi-standard compliance accelerates OEM onboarding</li>
<li><strong>Reduced tooling</strong>: No need for region-specific molds or production lines</li>
</ul>
<p>N.S.-LIN designs all tire valve products to comply with TRA, ETRTO, and JATMA specifications simultaneously, verified through our ISO 9001:2015 quality management system.</p>
<h2>Common Valve Types Across Standards</h2>
<p>The most widely used tire valve types are recognized across all three standards, though with different designation prefixes:</p>
<table class="w-full text-sm border-collapse my-6"><thead><tr class="border-b-2 border-slate-200"><th class="text-left py-2 px-3">Application</th><th class="text-left py-2 px-3">TRA</th><th class="text-left py-2 px-3">Type</th><th class="text-left py-2 px-3">Mounting</th></tr></thead><tbody><tr class="border-b border-slate-100"><td class="py-2 px-3">Passenger car</td><td class="py-2 px-3 font-medium">TR413 / TR414</td><td class="py-2 px-3">Snap-in rubber</td><td class="py-2 px-3">11.5mm rim hole</td></tr><tr class="border-b border-slate-100"><td class="py-2 px-3">High-speed / TPMS</td><td class="py-2 px-3 font-medium">TR416</td><td class="py-2 px-3">Clamp-in metal</td><td class="py-2 px-3">11.5mm rim hole</td></tr><tr class="border-b border-slate-100"><td class="py-2 px-3">Truck / bus</td><td class="py-2 px-3 font-medium">TR500 series</td><td class="py-2 px-3">Clamp-in metal</td><td class="py-2 px-3">Varies by application</td></tr><tr class="border-b border-slate-100"><td class="py-2 px-3">Motorcycle</td><td class="py-2 px-3 font-medium">TR412 / TR413</td><td class="py-2 px-3">Snap-in / clamp-in</td><td class="py-2 px-3">8.3mm or 11.5mm</td></tr></tbody></table>`,
  'valve-standards/zh-TW': `<h2>三大標準組織</h2>
<p>全球氣嘴閥產業受三大標準組織規範，各自代表一個主要汽車市場：</p>
<table class="w-full text-sm border-collapse my-6"><thead><tr class="border-b-2 border-slate-200"><th class="text-left py-2 px-3">組織</th><th class="text-left py-2 px-3">區域</th><th class="text-left py-2 px-3">範疇</th></tr></thead><tbody><tr class="border-b border-slate-100"><td class="py-2 px-3 font-medium">TRA（美國輪胎與輪圈協會）</td><td class="py-2 px-3">北美</td><td class="py-2 px-3">美國與加拿大市場的輪胎、輪圈及氣嘴閥標準</td></tr><tr class="border-b border-slate-100"><td class="py-2 px-3 font-medium">ETRTO（歐洲輪胎與輪圈技術組織）</td><td class="py-2 px-3">歐洲</td><td class="py-2 px-3">歐盟成員國的輪胎與氣嘴閥統一規範</td></tr><tr class="border-b border-slate-100"><td class="py-2 px-3 font-medium">JATMA（日本汽車輪胎製造商協會）</td><td class="py-2 px-3">日本</td><td class="py-2 px-3">日本國內輪胎、輪圈及氣嘴閥標準</td></tr></tbody></table>
<h2>主要差異</h2>
<p>三大標準在多數氣嘴閥類型的物理尺寸上相容，但在以下幾個重要面向有所不同：</p>
<h3>測試方法</h3>
<p>各組織定義各自的壓力保持、溫度循環和化學抗性測試規程。通過 TRA 測試的氣嘴閥，即使產品物理上完全相同，仍可能需要額外文件才能滿足 ETRTO 或 JATMA 要求。</p>
<h3>標記與文件</h3>
<ul>
<li><strong>TRA</strong>：要求特定英數字代號（如 TR413、TR414）</li>
<li><strong>ETRTO</strong>：使用自有代號系統，並交叉引用 TRA 對應編號</li>
<li><strong>JATMA</strong>：遵循日本工業標準（JIS）慣例，另有獨立的零件編號</li>
</ul>
<h3>區域認證</h3>
<p>各區域的 OEM 買家通常指定當地標準。歐洲車廠會引用 ETRTO 規範，日本車廠會引用 JATMA。對全球供應商而言，同時維護三套標準的合規文件至關重要。</p>
<h2>OEM 為何需要多標準合規</h2>
<p>對服務全球 OEM 客戶的氣嘴閥製造商而言，設計同時符合 TRA、ETRTO 與 JATMA 的產品，可消除區域專用產品變體的需求：</p>
<ul>
<li><strong>簡化庫存</strong>：一個 SKU 供應所有市場</li>
<li><strong>加速認證</strong>：預先取得多標準合規可加快 OEM 導入流程</li>
<li><strong>降低模具成本</strong>：無需區域專用模具或產線</li>
</ul>
<p>奕道實業所有氣嘴閥產品均設計為同時符合 TRA、ETRTO 與 JATMA 規範，透過 ISO 9001:2015 品質管理系統驗證。</p>
<h2>各標準通用氣嘴閥類型</h2>
<p>最廣泛使用的氣嘴閥類型在三大標準中均有對應，但使用不同的編號前綴：</p>
<table class="w-full text-sm border-collapse my-6"><thead><tr class="border-b-2 border-slate-200"><th class="text-left py-2 px-3">用途</th><th class="text-left py-2 px-3">TRA 編號</th><th class="text-left py-2 px-3">類型</th><th class="text-left py-2 px-3">安裝方式</th></tr></thead><tbody><tr class="border-b border-slate-100"><td class="py-2 px-3">乘用車</td><td class="py-2 px-3 font-medium">TR413 / TR414</td><td class="py-2 px-3">卡入式橡膠</td><td class="py-2 px-3">11.5mm 輪圈孔</td></tr><tr class="border-b border-slate-100"><td class="py-2 px-3">高速 / TPMS</td><td class="py-2 px-3 font-medium">TR416</td><td class="py-2 px-3">鎖固式金屬</td><td class="py-2 px-3">11.5mm 輪圈孔</td></tr><tr class="border-b border-slate-100"><td class="py-2 px-3">卡車 / 巴士</td><td class="py-2 px-3 font-medium">TR500 系列</td><td class="py-2 px-3">鎖固式金屬</td><td class="py-2 px-3">依用途而定</td></tr><tr class="border-b border-slate-100"><td class="py-2 px-3">機車</td><td class="py-2 px-3 font-medium">TR412 / TR413</td><td class="py-2 px-3">卡入式 / 鎖固式</td><td class="py-2 px-3">8.3mm 或 11.5mm</td></tr></tbody></table>`,
};
